name: test

on:
  push:
    branches:
       - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.7
        
        - name: ls
          run: |
            ls -al
            chmod +x script.sh
            ./script.sh

